import { execFile } from "node:child_process";
import { access, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const execFileAsync = promisify(execFile);

export type PrecommitProfile = "rust" | "python";
export type PrecommitRunner = "prek" | "pre-commit";

export type AddPrecommitOptions = {
  profiles: PrecommitProfile[];
  install: boolean;
  overwrite: boolean;
  help: boolean;
};

const VALID_PROFILES = new Set<PrecommitProfile>(["rust", "python"]);
const RUNNERS: PrecommitRunner[] = ["prek", "pre-commit"];
const COMMAND_TIMEOUT_MS = 30_000;

async function exists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function uniqueProfiles(profiles: PrecommitProfile[]): PrecommitProfile[] {
  const seen = new Set<PrecommitProfile>();
  const result: PrecommitProfile[] = [];
  for (const profile of profiles) {
    if (seen.has(profile)) continue;
    seen.add(profile);
    result.push(profile);
  }
  return result;
}

export function parseAddPrecommitArgs(args: string): AddPrecommitOptions {
  const tokens = args.split(/\s+/).map((token) => token.trim()).filter(Boolean);
  const profiles: PrecommitProfile[] = [];
  const options: AddPrecommitOptions = {
    profiles,
    install: true,
    overwrite: false,
    help: false,
  };

  for (const token of tokens) {
    const normalized = token.toLowerCase();
    if (normalized === "--help" || normalized === "-h") {
      options.help = true;
    } else if (normalized === "--no-install") {
      options.install = false;
    } else if (normalized === "--install") {
      options.install = true;
    } else if (normalized === "--force" || normalized === "--overwrite") {
      options.overwrite = true;
    } else if (VALID_PROFILES.has(normalized as PrecommitProfile)) {
      profiles.push(normalized as PrecommitProfile);
    } else {
      throw new Error(`Unknown /add-precommit argument: ${token}`);
    }
  }

  options.profiles = uniqueProfiles(profiles);
  return options;
}

export async function detectProfiles(root: string): Promise<PrecommitProfile[]> {
  const profiles: PrecommitProfile[] = [];
  if (await exists(path.join(root, "Cargo.toml"))) profiles.push("rust");

  const pythonFiles = ["pyproject.toml", "setup.py", "setup.cfg", "requirements.txt"];
  for (const file of pythonFiles) {
    if (await exists(path.join(root, file))) {
      profiles.push("python");
      break;
    }
  }

  return profiles;
}

export function buildPrecommitConfig(profiles: PrecommitProfile[]): string {
  const selected = new Set(uniqueProfiles(profiles));
  const lines = [
    "# Generated by /add-precommit.",
    "# Update hook versions periodically with `prek autoupdate` or `pre-commit autoupdate`.",
    "repos:",
    "  - repo: https://github.com/pre-commit/pre-commit-hooks",
    "    rev: v6.0.0",
    "    hooks:",
    "      - id: trailing-whitespace",
    "        args: [--markdown-linebreak-ext=md]",
    "      - id: end-of-file-fixer",
    "      - id: check-yaml",
    "      - id: check-toml",
    "      - id: check-json",
    "      - id: check-merge-conflict",
    "      - id: check-added-large-files",
    "      - id: detect-private-key",
    "      - id: check-case-conflict",
    "      - id: check-symlinks",
    "      - id: check-executables-have-shebangs",
    "      - id: check-shebang-scripts-are-executable",
    "  - repo: https://github.com/crate-ci/typos",
    "    rev: v1.47.2",
    "    hooks:",
    "      - id: typos",
    "        args: []",
  ];

  if (selected.has("python")) {
    lines.push(
      "  - repo: https://github.com/astral-sh/ruff-pre-commit",
      "    rev: v0.15.17",
      "    hooks:",
      "      - id: ruff-check",
      "        args: [--fix]",
      "      - id: ruff-format",
    );
  }

  if (selected.has("rust")) {
    lines.push(
      "  - repo: local",
      "    hooks:",
      "      - id: cargo-fmt",
      "        name: cargo fmt",
      "        entry: cargo fmt --all -- --check",
      "        language: system",
      "        pass_filenames: false",
      "        types: [rust]",
      "      - id: cargo-clippy",
      "        name: cargo clippy",
      "        entry: cargo clippy --workspace --all-targets --all-features -- -D warnings",
      "        language: system",
      "        pass_filenames: false",
      "        types: [rust]",
    );
  }

  return `${lines.join("\n")}\n`;
}

async function runCommand(command: string, args: string[], cwd: string): Promise<{ stdout: string; stderr: string }> {
  try {
    const { stdout, stderr } = await execFileAsync(command, args, {
      cwd,
      encoding: "utf-8",
      timeout: COMMAND_TIMEOUT_MS,
      maxBuffer: 1024 * 1024,
      env: {
        HOME: process.env.HOME ?? "",
        PATH: process.env.PATH ?? "",
        ...(process.env.SSH_AUTH_SOCK ? { SSH_AUTH_SOCK: process.env.SSH_AUTH_SOCK } : {}),
      },
    });
    return { stdout, stderr };
  } catch (error: any) {
    const output = String(error.stderr || error.stdout || error.message || "").trim();
    const suffix = output ? `: ${output.slice(0, 800)}` : "";
    throw new Error(`${command} ${args.join(" ")} failed${suffix}`);
  }
}

export async function getGitRoot(cwd: string): Promise<string> {
  const result = await runCommand("git", ["rev-parse", "--show-toplevel"], cwd);
  const root = result.stdout.trim();
  if (!root) throw new Error("Could not determine Git repository root.");
  return root;
}

export async function detectRunner(root: string): Promise<PrecommitRunner | null> {
  for (const runner of RUNNERS) {
    try {
      await runCommand(runner, ["--version"], root);
      return runner;
    } catch {
      // Try the next compatible runner.
    }
  }
  return null;
}

function configPath(root: string): string {
  return path.join(root, ".pre-commit-config.yaml");
}

async function existingConfig(root: string): Promise<string | null> {
  const yamlPath = configPath(root);
  if (await exists(yamlPath)) return yamlPath;
  const ymlPath = path.join(root, ".pre-commit-config.yml");
  if (await exists(ymlPath)) return ymlPath;
  return null;
}

function usage(): string {
  return [
    "Usage: /add-precommit [rust] [python] [--no-install] [--force]",
    "",
    "Examples:",
    "- /add-precommit rust",
    "- /add-precommit python",
    "- /add-precommit rust python",
    "- /add-precommit            # detect profiles from repository files",
  ].join("\n");
}

function confirmationSummary(input: {
  root: string;
  profiles: PrecommitProfile[];
  runner: PrecommitRunner | null;
  install: boolean;
  overwrite: boolean;
}): string {
  const installLine = input.install
    ? input.runner
      ? `Install Git hook with: ${input.runner} install`
      : "No `prek` or `pre-commit` executable found; only the config file will be written."
    : "Git hook installation skipped by --no-install.";

  return [
    `Repository: ${input.root}`,
    `Config: ${configPath(input.root)}`,
    `Profiles: ${input.profiles.join(", ")}`,
    `Overwrite existing config: ${input.overwrite ? "yes" : "no"}`,
    installLine,
  ].join("\n");
}

async function resolveProfiles(argsProfiles: PrecommitProfile[], root: string, ctx: any): Promise<PrecommitProfile[]> {
  if (argsProfiles.length > 0) return argsProfiles;

  const detected = await detectProfiles(root);
  if (detected.length > 0) return detected;

  if (ctx.hasUI !== false) {
    const answer = await ctx.ui.input("Profiles to add (rust, python):", "rust");
    if (typeof answer === "string" && answer.trim()) {
      return parseAddPrecommitArgs(answer).profiles;
    }
  }

  return [];
}

async function handleAddPrecommit(args: string, ctx: any): Promise<void> {
  await ctx.waitForIdle?.();
  const options = parseAddPrecommitArgs(args);
  if (options.help) {
    ctx.ui.notify(usage(), "info");
    return;
  }

  if (ctx.hasUI === false) {
    throw new Error("/add-precommit requires an interactive UI for the confirmation gate.");
  }

  const root = await getGitRoot(ctx.cwd);
  const existing = await existingConfig(root);
  if (existing && !options.overwrite) {
    throw new Error(`${existing} already exists. Re-run with --force to overwrite it.`);
  }

  const profiles = await resolveProfiles(options.profiles, root, ctx);
  if (profiles.length === 0) {
    throw new Error(`No profiles selected. ${usage()}`);
  }

  const runner = options.install ? await detectRunner(root) : null;
  const confirmed = await ctx.ui.confirm(
    "Add pre-commit configuration?",
    confirmationSummary({ root, profiles, runner, install: options.install, overwrite: options.overwrite }),
  );
  if (!confirmed) {
    ctx.ui.notify("Pre-commit setup cancelled.", "warning");
    return;
  }

  ctx.ui.setStatus?.("add-precommit", "Writing config");
  await writeFile(configPath(root), buildPrecommitConfig(profiles), { flag: options.overwrite ? "w" : "wx" });

  if (options.install && runner) {
    ctx.ui.setStatus?.("add-precommit", "Installing hook");
    await runCommand(runner, ["install"], root);
    ctx.ui.notify(`Wrote .pre-commit-config.yaml and installed hooks with ${runner}.`, "info");
  } else {
    ctx.ui.notify("Wrote .pre-commit-config.yaml. Install hooks with `prek install` or `pre-commit install`.", "info");
  }
  ctx.ui.setStatus?.("add-precommit", "Done");
}

export default function precommitSetup(pi: ExtensionAPI) {
  pi.registerCommand("add-precommit", {
    description: "Add a Rust and/or Python pre-commit configuration to the current repository",
    handler: async (args, ctx) => {
      try {
        await handleAddPrecommit(args ?? "", ctx);
      } catch (error: any) {
        ctx.ui.setStatus?.("add-precommit", "Failed");
        ctx.ui.notify(`Pre-commit setup stopped: ${error.message}`, "error");
      }
    },
  });
}
